// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjyBpT0xV34eQ0ojS48hg9sd93jDYiNqc',
    appId: '1:823932838004:web:982bfb24606403a74c3121',
    messagingSenderId: '823932838004',
    projectId: 'flutter-pushnotification-7bb17',
    authDomain: 'flutter-pushnotification-7bb17.firebaseapp.com',
    storageBucket: 'flutter-pushnotification-7bb17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5j50HdyL6f9UoStK8jSlBNHtuO9PiY0',
    appId: '1:823932838004:android:91afe1a4ed461e784c3121',
    messagingSenderId: '823932838004',
    projectId: 'flutter-pushnotification-7bb17',
    storageBucket: 'flutter-pushnotification-7bb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKuvHUq6lMKY1uaYqwCeuSvFOTWr8RppI',
    appId: '1:823932838004:ios:cbb1db50a8fcfe0c4c3121',
    messagingSenderId: '823932838004',
    projectId: 'flutter-pushnotification-7bb17',
    storageBucket: 'flutter-pushnotification-7bb17.appspot.com',
    iosBundleId: 'com.example.pushAppNew',
  );
}
